import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {mkdirSync,readFileSync} from 'node:fs';
import vm from 'node:vm';
import {defaults,THEMES,pebbleColor} from '../shared/settings.js';
import {PACKET_SIZE} from '../shared/protocol.js';
import {panelColors,PANEL_COLOR_ROLES} from '../shared/panel-settings.js';
mkdirSync('test-results',{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1200},timezoneId:'America/New_York'});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const base=process.env.PREVIEW_URL||'http://127.0.0.1:5173';
const saved=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('dymaxion-workshop-v1')));
const checkPixels=async()=>{
  const result=await page.locator('#screen').evaluate(canvas=>{
    const ctx=canvas.getContext('2d'),pixels=ctx.getImageData(0,0,200,228).data;
    let blended=0;for(let i=0;i<pixels.length;i+=4)if(pixels[i]%85||pixels[i+1]%85||pixels[i+2]%85||pixels[i+3]!==255)blended++;
    return {blended,smoothing:ctx.imageSmoothingEnabled,width:canvas.width,height:canvas.height};
  });
  assert.deepEqual(result,{blended:0,smoothing:false,width:200,height:228},'watch graphics use opaque native pixels without smoothing');
};
try{
  await page.goto(base);await page.waitForFunction(()=>document.querySelector('#preview-time').textContent.includes('LIVE'));
  await page.locator('#reset').click();
  await checkPixels();
  assert.equal(await page.locator('#widget0').count(),0);
  assert.equal(await page.locator('#moonIndicator').isChecked(),true);
  await page.locator('#element').selectOption('time');
  await page.locator('#pos-x').fill('5');await page.locator('#pos-x').press('Tab');assert.equal((await saved()).time[0],0);
  await page.locator('#pos-y').fill('22');await page.locator('#pos-y').press('Tab');assert.equal((await saved()).time[1],22);
  await page.locator('#screen').focus();await page.keyboard.press('Shift+ArrowDown');assert.equal((await saved()).time[1],27);
  await page.locator('#moonIndicator').uncheck();assert.equal((await saved()).moonIndicator,false);
  await page.getByRole('button',{name:'Horizon',exact:true}).click();assert.equal((await saved()).time[1],134);
  assert.equal((await saved()).moonIndicator,false);
  await page.locator('#moonIndicator').check();
  assert.equal(await page.getByRole('button',{name:'Original axis',exact:true}).count(),0);
  await page.getByRole('tab',{name:'Places',exact:true}).click();
  assert.equal(await page.locator('.marker-control canvas').first().evaluate(c=>c.clientWidth/c.width),3,'marker samples enlarge each pixel exactly three times');
  assert.equal(await page.locator('#marker-gallery .marker-tile').count(),5);
  assert.equal(await page.getByLabel('Symbol for place 1',{exact:true}).locator('option').count(),5);
  await page.getByLabel('Enable place 1',{exact:true}).uncheck();
  await page.getByLabel('Symbol for place 1',{exact:true}).selectOption('4');
  await page.getByLabel('Color for place 1',{exact:true}).fill('#cc7700');
  await page.getByLabel('Color for place 2',{exact:true}).fill('#00ff55');
  await page.getByLabel('City for place 1',{exact:true}).selectOption('9');
  let s=await saved();assert.equal(s.places[0].tz,'Asia/Kathmandu');assert.equal(s.places[0].on,false);assert.equal(s.places[0].icon,4);
  assert.equal(s.places[0].color,'#AA5500');assert.equal(s.places[1].color,'#00FF55');
  await page.getByLabel('Enable place 1',{exact:true}).check();
  await page.screenshot({path:'test-results/markers-workshop.png',fullPage:true});
  await page.locator('#marker-gallery').screenshot({path:'test-results/marker-gallery.png'});
  await page.getByLabel('Use theme color for place 1',{exact:true}).click();
  assert.equal((await saved()).places[0].color,null);assert.equal((await saved()).places[1].color,'#00FF55');
  await page.getByRole('tab',{name:'Character',exact:true}).click();await page.getByRole('button',{name:'Paper',exact:true}).click();
  await page.locator('#format').selectOption('2');s=await saved();assert.equal(s.theme,2);assert.equal(s.format,2);
  await page.reload();await page.waitForFunction(()=>document.querySelector('#preview-time').textContent.includes('LIVE'));assert.equal((await saved()).theme,2);
  const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export settings'}).click();const dl=await download;await dl.saveAs('test-results/export.json');
  assert.deepEqual(JSON.parse(readFileSync('test-results/export.json','utf8')),await saved());
  await page.locator('#import-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"version":99}')});await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('version 1'));assert.equal((await saved()).theme,2);
  await page.locator('#reset').click();
  await page.locator('#import-file').setInputFiles('test-results/export.json');await page.waitForFunction(()=>document.querySelector('#notice').textContent==='Composition imported.');assert.equal((await saved()).places[0].tz,'Asia/Kathmandu');
  await page.locator('#reset').click();await page.getByRole('button',{name:'Preview marker pulse'}).click();
  for(let i=0;i<4;i++){await page.waitForTimeout(260);await checkPixels();}
  await page.waitForTimeout(160);
  await page.screenshot({path:'test-results/workshop.png',fullPage:true});
  for(const preset of ['Atlas','Horizon']){await page.getByRole('button',{name:preset,exact:true}).click();await page.locator('#screen').screenshot({path:`test-results/preview-${preset}.png`});}
  await page.getByRole('button',{name:'Atlas',exact:true}).click();await page.getByRole('tab',{name:'Character',exact:true}).click();await page.screenshot({path:'test-results/type-specimen.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.getByRole('tab',{name:'Composition',exact:true}).click();
  await page.waitForFunction(()=>{const r=document.querySelector('#screen').getBoundingClientRect(),d=devicePixelRatio;return Math.abs((r.left+scrollX)*d-Math.round((r.left+scrollX)*d))<.005&&Math.abs((r.top+scrollY)*d-Math.round((r.top+scrollY)*d))<.005;});
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile overflow');await page.screenshot({path:'test-results/mobile.png',fullPage:true});
  // Exercise the actual generated companion against a simulated Pebble bridge.
  const handlers={},messages=[],store=new Map();let opened='';
  const context={console,Date,Math,Uint8Array,DataView,Array,Object,JSON,Number,String,RegExp,parseInt,parseFloat,isNaN,isFinite,decodeURIComponent,encodeURIComponent,setTimeout:fn=>{fn();return 1;},clearTimeout:()=>{},
    localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)},
    Pebble:{addEventListener:(name,fn)=>handlers[name]=fn,openURL:url=>opened=url,sendAppMessage:(message,success)=>{messages.push(message);success();}}};
  vm.runInNewContext(readFileSync('watchface/src/pkjs/index.js','utf8'),context);
  handlers.ready();assert.equal(messages[0].SETTINGS.length,PACKET_SIZE);
  assert.deepEqual(Array.from(messages[0].DISPLAY),[1,2,1,0]);
  handlers.showConfiguration();assert.ok(opened.startsWith('data:text/html;charset=utf-8,'));
  const mobile=await browser.newPage({viewport:{width:390,height:844}});mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(opened);
  assert.equal(await mobile.locator('#theme option').count(),THEMES.length);
  for(let theme=4;theme<THEMES.length;theme++){
    await mobile.locator('#theme').selectOption(String(theme));
    assert.equal((await mobile.getByLabel('Color for place 1',{exact:true}).inputValue()).toUpperCase(),THEMES[theme].marks[0]);
    const colored=defaults();colored.theme=theme;colored.places[0].color='#AA5500';
    handlers.webviewclosed({response:encodeURIComponent(JSON.stringify(colored))});
    const packet=messages.findLast(m=>m.SETTINGS).SETTINGS;
    assert.equal(packet[1],theme);assert.equal(packet[16+70],pebbleColor('#AA5500'));
    assert.equal(packet[16+72+70],pebbleColor(THEMES[theme].marks[1]));
    const colors=panelColors(colored),footer=messages.findLast(m=>m.FOOTER).FOOTER;
    assert.deepEqual(Array.from(footer).slice(21,29),PANEL_COLOR_ROLES.map(k=>pebbleColor(colors[k])));
    assert.equal((await mobile.getByLabel('Temperature panel color',{exact:true}).inputValue()).toUpperCase(),colors.temperature);
    assert.equal(JSON.parse(store.get('dymaxion-settings-v1')).theme,theme);
  }
  await mobile.locator('#preset').selectOption('horizon');await mobile.locator('#theme').selectOption('1');
  await mobile.locator('#stacked').check();
  assert.equal(await mobile.locator('#stacked').isChecked(),true);
  await mobile.locator('#moonIndicator').uncheck();assert.equal(await mobile.locator('#moonIndicator').isChecked(),false);
  assert.equal(await mobile.locator('[data-key=icon]').first().locator('option').count(),5);
  await mobile.locator('[data-key=icon]').first().selectOption('3');
  assert.match(await mobile.locator('[data-symbol-meaning]').first().textContent(),/directional triangle/);
  await mobile.getByLabel('Color for place 1',{exact:true}).fill('#cc7700');
  assert.match(await mobile.locator('[data-color-label]').first().textContent(),/#AA5500/);
  await mobile.getByText('Import settings from the workshop',{exact:true}).click();await mobile.locator('#json').fill(JSON.stringify({...defaults(),theme:3}));await mobile.getByRole('button',{name:'Load composition',exact:true}).click();assert.equal(await mobile.locator('#theme').inputValue(),'3');
  await mobile.getByLabel('Shake to change panels',{exact:true}).uncheck();
  await mobile.getByLabel('Numerical display',{exact:true}).selectOption('span');
  await mobile.getByLabel('Clock location',{exact:true}).selectOption('manual');
  await mobile.getByLabel('Clock city name',{exact:true}).fill('Norfolk');await mobile.getByLabel('Clock city name',{exact:true}).press('Tab');
  await mobile.locator('[data-key=label]').first().fill('HOME');await mobile.locator('[data-key=label]').first().press('Tab');
  await mobile.locator('#theme').selectOption('2');
  assert.equal(await mobile.locator('[data-key=label]').first().inputValue(),'HOME','editing panels must not detach other phone controls from saved settings');
  assert.equal(await mobile.getByLabel('Shake to change panels',{exact:true}).isChecked(),false);
  assert.equal(await mobile.getByLabel('Numerical display',{exact:true}).inputValue(),'span');
  assert.equal(await mobile.getByLabel('Clock city name',{exact:true}).inputValue(),'Norfolk');
  await mobile.screenshot({path:'test-results/offline-phone-settings.png',fullPage:true});
  const study=await browser.newPage({viewport:{width:1440,height:1200}});
  study.on('pageerror',e=>errors.push(e.message));
  await study.goto(new URL('type-study.html',base.endsWith('/')?base:`${base}/`).href);
  await study.waitForFunction(()=>document.querySelector('[data-family="span"] .figure-status').textContent.length>0);
  assert.equal(await study.locator('[data-family] canvas').count(),5);
  assert.equal(await study.locator('#study-error').textContent(),'');
  await study.locator('#study-time').selectOption('08:08');
  await study.locator('#study-figures').selectOption('oldstyle');
  assert.match(await study.locator('[data-family="span"] .figure-status').textContent(),/no oldstyle/);
  await study.screenshot({path:'test-results/type-study.png',fullPage:true});
  handlers.webviewclosed({response:encodeURIComponent(JSON.stringify({...defaults(),theme:3,clockDisplay:'span',location:{mode:'manual',name:'Norfolk'}}))});assert.equal(messages.findLast(m=>m.SETTINGS).SETTINGS[1],3);
  assert.deepEqual(Array.from(messages.findLast(m=>m.DISPLAY).DISPLAY),[1,0,1,0]);
  const city=Array.from(messages.findLast(m=>m.CITY).CITY);assert.equal(city.length,48);assert.equal(city[1],1);assert.equal(String.fromCharCode(...city.slice(8,15)),'Norfolk');
  const count=messages.filter(m=>m.SETTINGS).length;handlers.webviewclosed({response:'CANCELLED'});handlers.webviewclosed({response:'%broken'});assert.equal(messages.filter(m=>m.SETTINGS).length,count);
  assert.equal(JSON.parse(store.get('dymaxion-settings-v1')).theme,3);
  assert.deepEqual(errors,[]);console.log('PASS: two layouts, desktop/mobile controls, persistence, import/export, offline configuration and companion bridge.');
}finally{await browser.close();}
