import test from 'node:test';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {mkdirSync,writeFileSync} from 'node:fs';
import {encodeDisplay} from '../shared/display.js';
import {defaults,validateSettings} from '../shared/settings.js';
import {zoneExists} from '../shared/protocol.js';
test('display preferences migrate, validate, and travel separately from the stable layout packet',()=>{
  const s=defaults();assert.deepEqual([...encodeDisplay(s)],[2,4,0,0],'new faces use Chamfer figures');
  assert.deepEqual([...encodeDisplay({...s,clockDisplay:'broad'})],[2,2,0,0]);
  for(const clockDisplay of ['span','broad','chamfer','leco'])assert(![1,3].includes(encodeDisplay({...s,clockDisplay})[1]),'codes 1 and 3 are retired styles');
  assert.throws(()=>encodeDisplay({...s,clockDisplay:'triangles'}),'the triangular display is retired');
  assert(!('segmentGrid' in s));
  delete s.clockDisplay;
  assert.equal(validateSettings(s,zoneExists).clockDisplay,'broad');
  assert.throws(()=>validateSettings({...s,clockDisplay:'unknown'},zoneExists));
  const old=validateSettings({...s,clockDisplay:'triangles',segmentGrid:false},zoneExists);
  assert.equal(old.clockDisplay,'chamfer','saved triangular faces open as Chamfer');assert(!('segmentGrid' in old));
  assert.deepEqual([...encodeDisplay({...defaults(),clockDisplay:'span',leadingZero:false})],[2,0,2,0]);
  assert.equal(defaults().mapBackground,'none','the map background is off by default');
  assert.deepEqual([...encodeDisplay({...defaults(),mapBackground:'points'})],[2,4,0,1]);
  assert.deepEqual([...encodeDisplay({...defaults(),mapBackground:'lines'})],[2,4,0,2]);
  assert.deepEqual([...encodeDisplay({...defaults(),mapBackground:'fine-points'})],[2,4,0,3]);
  assert.equal(defaults().zoneTimes,'panel','place times stay in the panel by default');
  assert.equal(defaults().mapTimesTurn,false,'map times stay horizontal unless turning is allowed');
  assert.deepEqual([...encodeDisplay({...defaults(),zoneTimes:'when-hidden'})],[2,4,4,0]);
  assert.deepEqual([...encodeDisplay({...defaults(),zoneTimes:'always',leadingZero:false})],[2,4,10,0]);
  assert.deepEqual([...encodeDisplay({...defaults(),zonePosition:'map',mapTimesTurn:true})],[2,4,96,0],'bit 6: map times may turn');
  assert.equal(defaults().zonePosition,'left','place times sit left of the clock by default');
  assert.deepEqual([...encodeDisplay({...defaults(),zoneTimes:'always',zonePosition:'right'})],[2,4,24,0]);
  assert.deepEqual([...encodeDisplay({...defaults(),zoneTimes:'always',zonePosition:'map'})],[2,4,40,0]);
  assert.throws(()=>validateSettings({...s,zonePosition:'top'},zoneExists));
  assert.equal(defaults().nameplate,false,'the nameplate is off by default');
  assert.deepEqual([...encodeDisplay({...defaults(),nameplate:true})],[2,4,128,0],'bit 7: the Dymaxion nameplate');
  assert.equal(validateSettings({...s,zoneTimes:'always'},zoneExists).zoneTimes,'always');
  assert.equal(validateSettings(s,zoneExists).zoneTimes,'panel','older files keep place times in the panel');
  assert.throws(()=>validateSettings({...s,zoneTimes:'top'},zoneExists));
  assert.equal(validateSettings({...s,mapBackground:'lines'},zoneExists).mapBackground,'lines');
  assert.equal(validateSettings(s,zoneExists).mapBackground,'none','older files have no background');
  assert.throws(()=>validateSettings({...s,mapBackground:'stars'},zoneExists));
});
test('retired LCD and framing settings restore the open face without resetting personal preferences',()=>{
  const saved=defaults();saved.theme=2;saved.format=2;saved.time=[0,30];saved.map=[0,78];
  saved.location={mode:'manual',name:'Norfolk'};saved.places[0].color='#FF5500';
  saved.footer.home='weather';
  for(const clockDisplay of ['lcd','broad','span','triangles']){
    const expected=validateSettings({...saved,clockDisplay:{lcd:'broad',triangles:'chamfer'}[clockDisplay]??clockDisplay},zoneExists);
    const migrated=validateSettings({...saved,clockDisplay,framing:{style:'rails',clock:true,map:true,footer:true,grid:true}},zoneExists);
    assert.deepEqual(migrated,expected);
    assert(!('framing' in migrated));assert.equal(encodeDisplay(migrated)[3],0,'legacy framing never becomes a map background');
    assert.deepEqual(validateSettings(migrated,zoneExists),migrated,'migration is stable on subsequent saves');
  }
});
test('the watch migrates retired display codes and drops the unlit-grid bit',()=>{
  mkdirSync('test-results',{recursive:true});
  execFileSync('cc',['-std=c11','-Wall','-Wextra','-Werror','-Iwatchface/src/c','tests/display-test.c','watchface/src/c/display.c','-o','test-results/display-test']);
  execFileSync('test-results/display-test');
  writeFileSync('test-results/display-broad.bin',encodeDisplay({...defaults(),clockDisplay:'broad'}));
  writeFileSync('test-results/display-chamfer.bin',encodeDisplay(defaults()));
  writeFileSync('test-results/display-span.bin',encodeDisplay({...defaults(),clockDisplay:'span'}));
});
