import test from 'node:test';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {mkdirSync,readFileSync} from 'node:fs';
import {nameplateLayout,NAMEPLATE_ROWS,NAMEPLATE_WIDTH,NAMEPLATE_HEIGHT} from '../shared/nameplate.js';
import {PRESETS} from '../shared/settings.js';
const CASES=[[73,22,40,0,228],[73,20,46,0,228],[73,30,40,0,228],[24,134,40,0,228],[24,134,46,0,228],[24,134,40,0,177],[24,150,40,0,228],[24,142,40,0,228],[19,132,40,0,228],[73,0,84,1,228],[90,22,40,0,228],[60,22,40,0,228],[100,40,84,1,228],[24,60,84,1,228],[73,22,40,0,40]];
test('the watch places and draws the nameplate exactly as the workshop does',()=>{
  mkdirSync('test-results',{recursive:true});
  execFileSync('cc',['-std=c11','-Wall','-Wextra','-Werror','-Iwatchface/src/c','tests/nameplate-test.c','watchface/src/c/nameplate.c','watchface/src/c/settings.c','-o','test-results/nameplate-test']);
  const [spots,checksum]=execFileSync('test-results/nameplate-test',CASES.flat().map(String)).toString().trim().split('\n');
  assert.equal(spots.trim(),CASES.map(([mapY,timeY,height,stacked,visible])=>{const {plate,clockTop}=nameplateLayout({mapY,timeY,height,stacked:!!stacked,visible});return (plate?plate.x+','+plate.y:'-')+'@'+clockTop;}).join(' '));
  let count=0,sum=0;NAMEPLATE_ROWS.forEach((row,y)=>[...row].forEach((c,x)=>{if(c==='#'){count++;sum+=x*1000+y;}}));
  assert.equal(checksum,`${count} ${sum}`,'same pixels');
});
test('the nameplate fits Meridian above the map and Horizon below it',()=>{
  const m=PRESETS.meridian,{plate:spot,clockTop}=nameplateLayout({mapY:m.map[1],timeY:m.time[1],height:40});
  assert(spot,'Meridian has room');assert.equal(spot.x,(200-NAMEPLATE_WIDTH)>>1,'centred');assert.equal(clockTop,m.time[1],'the clock stays put');
  assert(spot.y>=m.time[1]+38+1,'a pixel clear of the clock\'s figures');
  assert.equal(spot.y+NAMEPLATE_HEIGHT-1,m.map[1]+6-2,'its last row a pixel above the map\'s net');
  const h=PRESETS.horizon,below=nameplateLayout({mapY:h.map[1],timeY:h.time[1],height:40});
  assert.deepEqual(below.plate,{x:spot.x,y:h.map[1]+97+3},'Horizon: two rows under the net');
  assert.equal(below.clockTop,h.time[1]+6,'the clock moves down six pixels');
  assert.equal(below.clockTop+2,below.plate.y+NAMEPLATE_HEIGHT+2,'two rows between the script and the figures');
  assert(below.clockTop+38<=184-6,'the figures still clear the bottom panel by six pixels');
  const peek=nameplateLayout({mapY:h.map[1],timeY:h.time[1],height:40,visible:177});
  assert.deepEqual(peek,{plate:null,clockTop:h.time[1]},'Quick View: the clock keeps its place and the script goes');
  assert.equal(nameplateLayout({mapY:73,timeY:30,height:40}).plate,null,'a lower clock leaves no room');
  const rows=JSON.parse(readFileSync('designer/public/type/identity.json'));
  assert.equal(NAMEPLATE_ROWS.join('').split('#').length-1,rows.flat().filter(Boolean).length,'every pixel of the script, trimmed');
});
