// Packs the Draft Micro lining capitals, figures and punctuation into a raw
// resource for the status line. The watch draws these runs directly, so its
// top line is pixel-identical to the workshop's drawBitmapText output.
import {readFileSync, writeFileSync, mkdirSync} from 'node:fs';
const font = JSON.parse(readFileSync('designer/public/type/draft.json', 'utf8')).lining.small;
const FIRST = 32, COUNT = 64, INDEX = 6;
const index = Buffer.alloc(COUNT * INDEX), runs = [];
for (let code = FIRST; code < FIRST + COUNT; code++) {
  const glyph = font[String.fromCharCode(code)], at = (code - FIRST) * INDEX;
  if (!glyph) { index.writeUInt8(0xff, at + 3); continue; }
  if (glyph.r.length > 254 || glyph.a > 255 || glyph.t > 255) throw new Error('Glyph out of range: ' + code);
  index.writeUInt8(glyph.a, at); index.writeInt8(glyph.l, at + 1); index.writeUInt8(glyph.t, at + 2);
  index.writeUInt8(glyph.r.length, at + 3); index.writeUInt16LE(runs.length / 3, at + 4);
  for (const [x, y, length] of glyph.r) runs.push(x, y, length);
}
if (!font['?']) throw new Error('The fallback glyph is missing.');
mkdirSync('watchface/resources/data', {recursive: true});
const out = Buffer.concat([index, Buffer.from(runs)]);
writeFileSync('watchface/resources/data/caps.bin', out);
writeFileSync('watchface/src/c/generated/caps_font.h', [
  '// Generated by tools/generate-caps.mjs. Layout of resources/data/caps.bin.',
  '#pragma once',
  `#define CAPS_FIRST ${FIRST}`, `#define CAPS_COUNT ${COUNT}`, `#define CAPS_INDEX_BYTES ${INDEX}`,
  `#define CAPS_RUNS_AT ${index.length}`, `#define CAPS_BYTES ${out.length}`, ''
].join('\n'));
console.log(`Generated status-line capitals: ${COUNT} slots, ${runs.length / 3} runs, ${out.length} bytes.`);
