import {mkdirSync,writeFileSync} from 'node:fs';
import {defaults,THEMES,MOON_COLORS} from '../shared/settings.js';
import {encodeSettings} from '../shared/protocol.js';
import {encodeFooter} from '../shared/panel-protocol.js';
import {encodeDisplay} from '../shared/triangle-display.js';
import {CITIES} from '../shared/cities.js';
import {makeMap,direction} from '../shared/map.js';
const map=makeMap();
mkdirSync('watchface/src/c/generated',{recursive:true});
// Deterministic seed; phone refreshes from the bundled IANA database on ready.
const packet=encodeSettings(defaults(),Date.UTC(2026,0,1));
writeFileSync('watchface/src/c/generated/footer_defaults.h',`// Generated by npm run generate.\nstatic const uint8_t DEFAULT_FOOTER[64] = {${Array.from(encodeFooter(defaults()))}};\n`);
const byte=c=>0xc0|(parseInt(c.slice(1,3),16)/85<<4)|(parseInt(c.slice(3,5),16)/85<<2)|(parseInt(c.slice(5,7),16)/85);
writeFileSync('watchface/src/c/generated/palette_sizes.h',`// Generated by npm run generate; do not edit.\n#pragma once\n#define THEME_COUNT ${THEMES.length}\n`);
writeFileSync('watchface/src/c/generated/defaults.h',`// Generated by npm run generate; do not edit.\n#include "palette_sizes.h"\nstatic const uint8_t DEFAULT_SETTINGS[232] = {${Array.from(packet)}};\n#define DEFAULT_DISPLAY {${Array.from(encodeDisplay(defaults()))}}\nstatic const uint8_t PALETTE_ZONE_GLYPHS[THEME_COUNT] = {${THEMES.map(t=>+!!t.zoneGlyphs)}};\nstatic const uint8_t PALETTES[THEME_COUNT][11] = {\n${THEMES.map(t=>`  {${[t.bg,t.ocean,t.land,t.nightOcean,t.nightLand,t.edge,t.ink,t.accent,...t.marks].map(byte)}}`).join(',\n')}\n};\n`);
writeFileSync('watchface/src/c/generated/moon_palette.h',`// Generated by npm run generate; do not edit.\n#include "palette_sizes.h"\nstatic const uint8_t MOON_PALETTES[THEME_COUNT][3] = {\n${MOON_COLORS.map(colors=>`  {${colors.map(byte)}}`).join(',\n')}\n};\n`);
console.log('Default packet and RGB222 palettes generated.');
writeFileSync('watchface/src/c/generated/cities.h',`// Generated from original concept population centers.\ntypedef struct { uint8_t x,y; int8_t dx,dy,dz; uint8_t magnitude; } City;\n#define CITY_COUNT ${CITIES.length}\nstatic const City CITIES[CITY_COUNT] = {\n${CITIES.map(([lat,lon,mag])=>{return '{'+[...map.project(lat,lon).map(Math.round),...direction(lat,lon).map(v=>Math.round(v*127)),mag].join(',')+'}';}).join(',')}\n};\n`);
