import {mkdirSync,writeFileSync} from 'node:fs';
import {MARKERS,MARKER_SIZE} from '../shared/markers.js';
if(MARKERS.length<3||MARKERS.length>16)throw new Error('Expected a small set of map glyphs.');
const seen=new Set();
for(const [index,marker] of MARKERS.entries()){
  if(marker.rows.length!==MARKER_SIZE||marker.rows.some(row=>row.length!==MARKER_SIZE||/[^.#]/.test(row)))
    throw new Error(`Invalid pixel master for ${marker.name} (${index}).`);
  const pixels=marker.rows.join('');
  if(seen.has(pixels))throw new Error(`Repeated map symbol: ${marker.name}.`);
  seen.add(pixels);
}
const values=MARKERS.map(marker=>'{'+marker.rows.map(row=>parseInt(row.replaceAll('.','0').replaceAll('#','1'),2)).join(',')+'}');
mkdirSync('watchface/src/c/generated',{recursive:true});
writeFileSync('watchface/src/c/generated/markers.h',
  '// Generated by tools/generate-markers.mjs from shared/markers.js.\n'
  +`#if MARKER_COUNT != ${MARKERS.length}\n#error MARKER_COUNT must match shared/markers.js\n#endif\n`
  +`#define MARKER_SIZE ${MARKER_SIZE}\n`
  +`static const uint16_t MARKER_ROWS[MARKER_COUNT][MARKER_SIZE] = {\n  ${values.join(',\n  ')}\n};\n`);
console.log(`${MARKERS.length} original ${MARKER_SIZE}×${MARKER_SIZE} map glyphs generated.`);
