"""Original Dymaxion angular script, authored on an 124x17 pixel grid.

This is a wordmark, not a font conversion. Every stroke is specified here;
no font file, reference artwork, outline tracing or antialiasing is used.
Project license: Apache-2.0.
"""
import json
from pathlib import Path
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
WIDTH, HEIGHT = 124, 17
# Low, wide lowercase and long baseline joins evoke an appliance nameplate.
# The original geometry is authored at native size, with a taller swept capital.
STROKES = [
    # D: wide shoulder, shallow bowl and a decisive forward stem.
    [(2,5),(4,2),(12,1),(17,3),(18,5),(17,8),(14,10),(10,11),(2,11)],
    [(8,2),(5,10),(4,12)],
    [(10,11),(21,11)],
    # y: low fork with a compact return below the common baseline.
    [(23,6),(22,10),(23,11),(27,11),(30,6),(29,11),(28,14),(26,16),(23,16),(22,15),(24,13),(31,11),(35,11)],
    # m: two shallow shoulders separated by open triangular counters.
    [(35,11),(37,6),(38,6),(37,10),(40,7),(42,6),(44,7),(43,10),(46,7),(48,6),(50,7),(49,10),(50,11),(55,11)],
    # a: broad bowl and an independent short exit stem.
    [(55,11),(57,7),(59,6),(64,6),(64,8),(62,11),(58,11),(56,10),(57,7)],
    [(64,6),(62,10),(63,11),(69,11)],
    # x: a low, wide crossing, connected along the baseline.
    [(70,6),(73,6),(77,11),(81,11)],
    [(77,6),(70,11),(67,11)],
    # i: clipped stem, open spacing and a clear dot.
    [(81,11),(84,6),(85,6),(83,10),(84,11),(89,11)],
    [(85,3),(85,3)],
    # o: an open, wide counter with a level exit.
    [(89,11),(91,7),(93,6),(98,6),(99,8),(97,11),(93,11),(91,9),(91,7)],
    [(97,11),(103,11)],
    # n: shallow shoulder and the final extended chrome-strip gesture.
    [(103,11),(105,6),(106,6),(105,10),(109,6),(112,6),(113,8),(111,10),(112,11),(118,11),(122,9)],
]

mask = Image.new('1', (WIDTH, HEIGHT))
draw = ImageDraw.Draw(mask)
for points in STROKES:
    draw.line(points, fill=1, width=1)
rows = [[3 if mask.getpixel((x,y)) else 0 for x in range(WIDTH)] for y in range(HEIGHT)]
public = ROOT / 'designer/public'
(public / 'type/identity.json').write_text(json.dumps(rows, separators=(',',':')))
header = '// Generated by tools/generate-wordmark.py. Original Dymaxion pixel script. Apache-2.0.\n'
header += f'#pragma once\n#define IDENTITY_WIDTH {WIDTH}\n#define IDENTITY_HEIGHT {HEIGHT}\n'
header += 'static const uint8_t IDENTITY_ALPHA[] = {' + ','.join(str(a) for row in rows for a in row) + '};\n'
(ROOT / 'watchface/src/c/generated/identity.h').write_text(header)
rects = ''.join(f'<rect x="{x}" y="{y}" width="1" height="1"/>' for y,row in enumerate(rows) for x,a in enumerate(row) if a)
(public / 'brand/dymaxion-wordmark.svg').write_text(
    f'<svg xmlns="http://www.w3.org/2000/svg" width="{WIDTH}" height="{HEIGHT}" viewBox="0 0 {WIDTH} {HEIGHT}" shape-rendering="crispEdges">'
    '<title>Dymaxion — original pixel script</title><desc>Hand-drawn angular script on the watch pixel grid. Apache-2.0.</desc><g fill="#254e42">' + rects + '</g></svg>\n')
print(f'Original pixel script: {WIDTH}x{HEIGHT}, solid one-pixel strokes, no external font.')

if __name__ == '__main__':
    # Development proof only; use integer enlargement, preserving the master.
    proof = Image.new('RGB', (WIDTH*8, HEIGHT*8+36), '#f1efe6')
    colored = Image.new('RGB', (WIDTH,HEIGHT), '#f1efe6')
    colored.paste('#254e42', mask=mask)
    proof.paste(colored.resize((WIDTH*8,HEIGHT*8),Image.Resampling.NEAREST),(0,0))
    proof.paste(colored,(8,HEIGHT*8+12))
    path = ROOT / 'test-results/wordmark-proof.png'
    path.parent.mkdir(exist_ok=True)
    proof.save(path)
