// The triangle net as small integer tables, so the watch and the previews can
// project a direction (the Sun, the Moon) straight onto the map instead of
// searching every map pixel for the closest one. Writes the C header and the
// matching JS module (shared/map-net.js projects with the same numbers).
import {writeFileSync} from 'node:fs';
import {V,GF,makeMap} from '../shared/map.js';

export const NET_V_SCALE=32767,NET_PX_SCALE=128;
const m=makeMap();
const vertices=V.map(v=>v.map(c=>Math.round(c*NET_V_SCALE)));
const faces=GF;
// Each placement: its face, the LCD sixths it holds (bit l-1 for sixth l; 0 for
// the whole face), and its corners in map pixels (x NET_PX_SCALE).
const placements=m.T.map(t=>({face:GF.indexOf(t.f),lcd:(t.lcd||[]).reduce((b,l)=>b|1<<(l-1),0),
  corners:t.p.map(p=>m.toPixel(p).map(c=>Math.round(c*NET_PX_SCALE)))}));
if(placements.some(p=>p.face<0))throw new Error('placement without a face');

const c=`// Generated by tools/generate-map-net.mjs; do not edit.
#pragma once
#include <stdint.h>
#define NET_V_SCALE ${NET_V_SCALE}
#define NET_PX_SCALE ${NET_PX_SCALE}
#define NET_PLACEMENT_COUNT ${placements.length}
typedef struct {uint8_t face,lcd;int16_t corner[3][2];} NetPlacement;
static const int16_t NET_VERTICES[12][3]={${vertices.map(v=>'{'+v.join(',')+'}').join(',')}};
static const uint8_t NET_FACES[20][3]={${faces.map(f=>'{'+f.join(',')+'}').join(',')}};
static const NetPlacement NET_PLACEMENTS[NET_PLACEMENT_COUNT]={${placements.map(p=>`{${p.face},${p.lcd},{${p.corners.map(q=>'{'+q.join(',')+'}').join(',')}}}`).join(',')}};
`;
writeFileSync('watchface/src/c/generated/map_net.h',c);
const js=`// Generated by tools/generate-map-net.mjs; do not edit.
export const NET_V_SCALE=${NET_V_SCALE},NET_PX_SCALE=${NET_PX_SCALE};
export const NET_VERTICES=${JSON.stringify(vertices)};
export const NET_FACES=${JSON.stringify(faces)};
export const NET_PLACEMENTS=${JSON.stringify(placements)};
`;
writeFileSync('shared/map-net-data.js',js);
console.log(`Map net: ${vertices.length} vertices, ${faces.length} faces, ${placements.length} placements.`);
